// Full species roster — 60 creatures.
// Schema: baseAtk/baseDef/baseSta match stats.js computeCP/computeHP.
// biomes: weights per biome key (spawn engine uses these directly).
// time: weights for day/night (spawn engine uses these).

export const RARITY_BCR = {
  common:    0.50,
  uncommon:  0.30,
  rare:      0.15,
  epic:      0.06,
  legendary: 0.02,
}

export const RARITY_WEIGHT = {
  common:    100,
  uncommon:   40,
  rare:       12,
  epic:        3,
  legendary:   0, // legendaries don't spawn wild yet
}

// Biome weight templates
const BW = {
  grass:  { grass: 10, park: 6, forest: 2 },
  water:  { water: 10, park: 2 },
  urban:  { urban: 10, park: 3, grass: 1 },
  forest: { forest: 10, park: 5, grass: 2 },
  cave:   { cave: 10, urban: 2 },
  sky:    { sky: 10, park: 4, urban: 2, grass: 2 },
}

// Time weight templates
const TW = {
  day:   { day: 7, night: 2 },
  night: { day: 1, night: 10 },
  even:  { day: 5, night: 5 },
  dawn:  { day: 0, night: 10 },
}

export const SPECIES = [
  // ── GRASS ──────────────────────────────────────────────────────────────────
  {
    id: 'pufftail', name: 'Pufftail', emoji: '🌿',
    types: ['grass'],
    baseAtk: 58, baseDef: 48, baseSta: 62,
    bcr: 0.50, fleeRate: 0.20, rarity: 'common',
    biomes: BW.grass, time: TW.day,
    candy: 'pufftail', evolvesTo: 'thornwick', evolveCost: 12,
    desc: 'A soft round creature bouncing between blades of grass.',
  },
  {
    id: 'thornwick', name: 'Thornwick', emoji: '🌿',
    types: ['grass'],
    baseAtk: 78, baseDef: 72, baseSta: 74,
    bcr: 0.30, fleeRate: 0.15, rarity: 'uncommon',
    biomes: BW.grass, time: TW.day,
    candy: 'pufftail', evolvesTo: 'bloomguard', evolveCost: 25,
    desc: 'A dense thicket of living vines with a single glowing eye.',
  },
  {
    id: 'bloomguard', name: 'Bloomguard', emoji: '🌺',
    types: ['grass'],
    baseAtk: 108, baseDef: 112, baseSta: 96,
    bcr: 0.15, fleeRate: 0.10, rarity: 'rare',
    biomes: BW.grass, time: TW.day,
    candy: 'pufftail', evolvesTo: null, evolveCost: 0,
    desc: 'A towering guardian of meadows whose bloom opens only at dawn.',
  },
  {
    id: 'dustmoth', name: 'Dustmoth', emoji: '🦋',
    types: ['bug'],
    baseAtk: 45, baseDef: 40, baseSta: 52,
    bcr: 0.50, fleeRate: 0.35, rarity: 'common',
    biomes: BW.grass, time: TW.day,
    candy: 'dustmoth', evolvesTo: 'silkwraith', evolveCost: 12,
    desc: 'A tiny moth drifting through sunbeams, leaving trails of iridescent dust.',
  },
  {
    id: 'silkwraith', name: 'Silkwraith', emoji: '🦋',
    types: ['bug', 'ghost'],
    baseAtk: 82, baseDef: 65, baseSta: 58,
    bcr: 0.15, fleeRate: 0.25, rarity: 'rare',
    biomes: BW.grass, time: TW.even,
    candy: 'dustmoth', evolvesTo: null, evolveCost: 0,
    desc: 'A translucent moth whose wings spin fast enough to blur into a ghostly afterimage.',
  },
  {
    id: 'pollenspore', name: 'Pollenspore', emoji: '🌸',
    types: ['grass'],
    baseAtk: 48, baseDef: 52, baseSta: 65,
    bcr: 0.50, fleeRate: 0.30, rarity: 'common',
    biomes: BW.grass, time: TW.day,
    candy: 'pollenspore', evolvesTo: 'nectorose', evolveCost: 12,
    desc: 'A tiny spore that drifts on the wind and settles on petals.',
  },
  {
    id: 'nectorose', name: 'Nectorose', emoji: '🌹',
    types: ['grass'],
    baseAtk: 92, baseDef: 85, baseSta: 78,
    bcr: 0.30, fleeRate: 0.15, rarity: 'uncommon',
    biomes: BW.grass, time: TW.day,
    candy: 'pollenspore', evolvesTo: 'veridante', evolveCost: 25,
    desc: 'A rose-like creature that releases a soothing scent. Bees orbit it in lazy circles.',
  },
  {
    id: 'veridante', name: 'Veridante', emoji: '🌳',
    types: ['grass', 'dragon'],
    baseAtk: 132, baseDef: 118, baseSta: 95,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.grass, time: TW.day,
    candy: 'pollenspore', evolvesTo: null, evolveCost: 0,
    desc: 'An ancient flower-dragon whose breath grows forests overnight.',
  },
  {
    id: 'sandshrike', name: 'Sandshrike', emoji: '🦔',
    types: ['ground'],
    baseAtk: 75, baseDef: 82, baseSta: 68,
    bcr: 0.50, fleeRate: 0.20, rarity: 'common',
    biomes: BW.grass, time: TW.day,
    candy: 'sandshrike', evolvesTo: 'duneserpent', evolveCost: 12,
    desc: 'A spiny creature that rolls into a ball and tumbles across dunes.',
  },
  {
    id: 'duneserpent', name: 'Duneserpent', emoji: '🐍',
    types: ['ground', 'flying'],
    baseAtk: 125, baseDef: 98, baseSta: 85,
    bcr: 0.15, fleeRate: 0.12, rarity: 'rare',
    biomes: BW.grass, time: TW.day,
    candy: 'sandshrike', evolvesTo: null, evolveCost: 0,
    desc: 'A winged serpent that soars over dunes, its scales invisible against sand.',
  },

  // ── WATER ──────────────────────────────────────────────────────────────────
  {
    id: 'bubblefin', name: 'Bubblefin', emoji: '🐟',
    types: ['water'],
    baseAtk: 52, baseDef: 55, baseSta: 60,
    bcr: 0.50, fleeRate: 0.25, rarity: 'common',
    biomes: BW.water, time: TW.even,
    candy: 'bubblefin', evolvesTo: 'coralwisp', evolveCost: 12,
    desc: 'A small fish that builds bubbles into perfect spheres.',
  },
  {
    id: 'coralwisp', name: 'Coralwisp', emoji: '🪼',
    types: ['water'],
    baseAtk: 88, baseDef: 85, baseSta: 72,
    bcr: 0.30, fleeRate: 0.15, rarity: 'uncommon',
    biomes: BW.water, time: TW.even,
    candy: 'bubblefin', evolvesTo: 'tidalord', evolveCost: 25,
    desc: 'A luminescent jellyfish drifting between tidal pools.',
  },
  {
    id: 'tidalord', name: 'Tidalord', emoji: '🐉',
    types: ['water', 'dragon'],
    baseAtk: 135, baseDef: 128, baseSta: 102,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.water, time: TW.even,
    candy: 'bubblefin', evolvesTo: null, evolveCost: 0,
    desc: 'A serpentine leviathan that surfaces only during spring tides.',
  },
  {
    id: 'splashkit', name: 'Splashkit', emoji: '💧',
    types: ['water'],
    baseAtk: 60, baseDef: 50, baseSta: 58,
    bcr: 0.50, fleeRate: 0.30, rarity: 'common',
    biomes: BW.water, time: TW.day,
    candy: 'splashkit', evolvesTo: null, evolveCost: 0,
    desc: 'A playful creature that splashes water into the air.',
  },
  {
    id: 'mirelurk', name: 'Mirelurk', emoji: '🦀',
    types: ['water', 'bug'],
    baseAtk: 68, baseDef: 78, baseSta: 65,
    bcr: 0.30, fleeRate: 0.20, rarity: 'uncommon',
    biomes: BW.water, time: TW.even,
    candy: 'mirelurk', evolvesTo: 'dredgemaw', evolveCost: 25,
    desc: 'A crab-like creature that burrows into marsh mud and ambushes prey.',
  },
  {
    id: 'dredgemaw', name: 'Dredgemaw', emoji: '🦞',
    types: ['water', 'rock'],
    baseAtk: 112, baseDef: 138, baseSta: 88,
    bcr: 0.15, fleeRate: 0.10, rarity: 'rare',
    biomes: BW.water, time: TW.even,
    candy: 'mirelurk', evolvesTo: null, evolveCost: 0,
    desc: 'A massive armored crustacean that sinks into lake beds for years.',
  },
  {
    id: 'frostfang', name: 'Frostfang', emoji: '🐺',
    types: ['ice'],
    baseAtk: 58, baseDef: 62, baseSta: 55,
    bcr: 0.50, fleeRate: 0.25, rarity: 'common',
    biomes: BW.water, time: TW.even,
    candy: 'frostfang', evolvesTo: 'glacierhowl', evolveCost: 12,
    desc: 'A small wolf with fur that freezes to blue-white. It breathes visible frost.',
  },
  {
    id: 'glacierhowl', name: 'Glacierhowl', emoji: '❄️',
    types: ['ice', 'flying'],
    baseAtk: 102, baseDef: 95, baseSta: 78,
    bcr: 0.15, fleeRate: 0.12, rarity: 'rare',
    biomes: BW.water, time: TW.even,
    candy: 'frostfang', evolvesTo: null, evolveCost: 0,
    desc: 'A winged wolf that soars over frozen lakes. Its howl crystallizes the air.',
  },
  {
    id: 'mudling', name: 'Mudling', emoji: '🌊',
    types: ['ground'],
    baseAtk: 55, baseDef: 72, baseSta: 48,
    bcr: 0.50, fleeRate: 0.20, rarity: 'common',
    biomes: BW.water, time: TW.day,
    candy: 'mudling', evolvesTo: null, evolveCost: 0,
    desc: 'A small blob of living mud that latches onto ankles for fun.',
  },

  // ── ELECTRIC / URBAN ───────────────────────────────────────────────────────
  {
    id: 'sparkwisp', name: 'Sparkwisp', emoji: '⚡',
    types: ['electric'],
    baseAtk: 65, baseDef: 45, baseSta: 48,
    bcr: 0.50, fleeRate: 0.40, rarity: 'common',
    biomes: BW.urban, time: TW.even,
    candy: 'sparkwisp', evolvesTo: 'voltmuse', evolveCost: 12,
    desc: 'A tiny crackling orb of static electricity that zaps passing creatures for fun.',
  },
  {
    id: 'voltmuse', name: 'Voltmuse', emoji: '⚡',
    types: ['electric', 'flying'],
    baseAtk: 112, baseDef: 78, baseSta: 62,
    bcr: 0.15, fleeRate: 0.15, rarity: 'rare',
    biomes: BW.urban, time: TW.even,
    candy: 'sparkwisp', evolvesTo: null, evolveCost: 0,
    desc: 'A hummingbird-shaped creature whose wings generate enough voltage to light a room.',
  },
  {
    id: 'thundervale', name: 'Thundervale', emoji: '🌩️',
    types: ['electric'],
    baseAtk: 95, baseDef: 88, baseSta: 75,
    bcr: 0.30, fleeRate: 0.15, rarity: 'uncommon',
    biomes: BW.urban, time: TW.even,
    candy: 'thundervale', evolvesTo: 'stormcrown', evolveCost: 25,
    desc: 'A cat-like creature with lightning-bolt stripes that pounces on actual bolts.',
  },
  {
    id: 'stormcrown', name: 'Stormcrown', emoji: '🌩️',
    types: ['electric', 'dragon'],
    baseAtk: 158, baseDef: 125, baseSta: 95,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.urban, time: TW.even,
    candy: 'thundervale', evolvesTo: null, evolveCost: 0,
    desc: 'A winged serpent wreathed in perpetual thunderstorms.',
  },
  {
    id: 'thunderbuck', name: 'Thunderbuck', emoji: '🦌',
    types: ['electric', 'ground'],
    baseAtk: 88, baseDef: 75, baseSta: 68,
    bcr: 0.30, fleeRate: 0.18, rarity: 'uncommon',
    biomes: BW.urban, time: TW.day,
    candy: 'thunderbuck', evolvesTo: 'voltstag', evolveCost: 25,
    desc: 'A deer-like creature with antlers of living lightning.',
  },
  {
    id: 'voltstag', name: 'Voltstag', emoji: '🦌',
    types: ['electric', 'dragon'],
    baseAtk: 132, baseDef: 108, baseSta: 85,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.urban, time: TW.day,
    candy: 'thunderbuck', evolvesTo: null, evolveCost: 0,
    desc: 'A stag wreathed in perpetual lightning. Its antlers could power a small city.',
  },
  {
    id: 'gearmite', name: 'Gearmite', emoji: '⚙️',
    types: ['steel'],
    baseAtk: 58, baseDef: 88, baseSta: 50,
    bcr: 0.50, fleeRate: 0.15, rarity: 'common',
    biomes: BW.urban, time: TW.day,
    candy: 'gearmite', evolvesTo: 'cogwarden', evolveCost: 12,
    desc: 'A small mechanical creature with a single gear for an eye.',
  },
  {
    id: 'cogwarden', name: 'Cogwarden', emoji: '🤖',
    types: ['steel', 'dark'],
    baseAtk: 110, baseDef: 135, baseSta: 75,
    bcr: 0.15, fleeRate: 0.10, rarity: 'rare',
    biomes: BW.urban, time: TW.day,
    candy: 'gearmite', evolvesTo: null, evolveCost: 0,
    desc: 'A heavy armored guardian whose pistons fire like a drumline.',
  },
  {
    id: 'rivetwraith', name: 'Rivetwraith', emoji: '👾',
    types: ['steel', 'ghost'],
    baseAtk: 85, baseDef: 72, baseSta: 60,
    bcr: 0.30, fleeRate: 0.20, rarity: 'uncommon',
    biomes: BW.urban, time: TW.night,
    candy: 'rivetwraith', evolvesTo: 'ironphasma', evolveCost: 25,
    desc: 'A translucent machine that phases through walls — the ghost of a factory.',
  },
  {
    id: 'ironphasma', name: 'Ironphasma', emoji: '🤖',
    types: ['steel', 'dragon'],
    baseAtk: 138, baseDef: 128, baseSta: 88,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.urban, time: TW.night,
    candy: 'rivetwraith', evolvesTo: null, evolveCost: 0,
    desc: 'A colossal spectral mech — the ghost of the first machine ever built.',
  },
  {
    id: 'punchkit', name: 'Punchkit', emoji: '👊',
    types: ['fighting'],
    baseAtk: 82, baseDef: 65, baseSta: 58,
    bcr: 0.50, fleeRate: 0.25, rarity: 'common',
    biomes: BW.urban, time: TW.day,
    candy: 'punchkit', evolvesTo: 'ironfist', evolveCost: 12,
    desc: 'A small muscular creature that trains by punching air.',
  },
  {
    id: 'ironfist', name: 'Ironfist', emoji: '👊',
    types: ['fighting', 'steel'],
    baseAtk: 128, baseDef: 108, baseSta: 72,
    bcr: 0.15, fleeRate: 0.10, rarity: 'rare',
    biomes: BW.urban, time: TW.day,
    candy: 'punchkit', evolvesTo: null, evolveCost: 0,
    desc: 'A heavyweight boxer with fists of compressed steel.',
  },
  {
    id: 'daggerwing', name: 'Daggerwing', emoji: '🦇',
    types: ['fighting', 'dark'],
    baseAtk: 112, baseDef: 78, baseSta: 68,
    bcr: 0.30, fleeRate: 0.18, rarity: 'uncommon',
    biomes: BW.urban, time: TW.night,
    candy: 'daggerwing', evolvesTo: 'shadowblade', evolveCost: 25,
    desc: 'A sleek creature with blade-shaped wings that strikes from above.',
  },
  {
    id: 'shadowblade', name: 'Shadowblade', emoji: '🗡️',
    types: ['fighting', 'dragon'],
    baseAtk: 145, baseDef: 112, baseSta: 85,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.urban, time: TW.night,
    candy: 'daggerwing', evolvesTo: null, evolveCost: 0,
    desc: 'A winged warrior that fights in complete silence.',
  },

  // ── FIRE / CAVE ────────────────────────────────────────────────────────────
  {
    id: 'emberpup', name: 'Emberpup', emoji: '🦊',
    types: ['fire'],
    baseAtk: 72, baseDef: 55, baseSta: 60,
    bcr: 0.50, fleeRate: 0.25, rarity: 'common',
    biomes: BW.cave, time: TW.even,
    candy: 'emberpup', evolvesTo: 'flamewarden', evolveCost: 12,
    desc: 'A small fox-like creature with a tail that smolders like a torch.',
  },
  {
    id: 'flamewarden', name: 'Flamewarden', emoji: '🔥',
    types: ['fire'],
    baseAtk: 105, baseDef: 88, baseSta: 72,
    bcr: 0.30, fleeRate: 0.15, rarity: 'uncommon',
    biomes: BW.cave, time: TW.even,
    candy: 'emberpup', evolvesTo: 'pyrathane', evolveCost: 25,
    desc: 'A guardian of volcanic forges. Its flames burn blue when calm, white when enraged.',
  },
  {
    id: 'pyrathane', name: 'Pyrathane', emoji: '🐉',
    types: ['fire', 'dragon'],
    baseAtk: 148, baseDef: 132, baseSta: 98,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.cave, time: TW.even,
    candy: 'emberpup', evolvesTo: null, evolveCost: 0,
    desc: 'A dragon forged in magma whose breath ignites the air.',
  },
  {
    id: 'cinderburr', name: 'Cinderburr', emoji: '🔥',
    types: ['fire'],
    baseAtk: 55, baseDef: 62, baseSta: 48,
    bcr: 0.50, fleeRate: 0.35, rarity: 'common',
    biomes: BW.cave, time: TW.even,
    candy: 'cinderburr', evolvesTo: null, evolveCost: 0,
    desc: 'A round spiky creature that releases sparks when startled.',
  },
  {
    id: 'pebbleclaw', name: 'Pebbleclaw', emoji: '🪨',
    types: ['rock'],
    baseAtk: 68, baseDef: 92, baseSta: 55,
    bcr: 0.50, fleeRate: 0.15, rarity: 'common',
    biomes: BW.cave, time: TW.day,
    candy: 'pebbleclaw', evolvesTo: 'bouldermaw', evolveCost: 12,
    desc: 'A small creature with granite claws that stores pebbles like a squirrel.',
  },
  {
    id: 'bouldermaw', name: 'Bouldermaw', emoji: '🪨',
    types: ['rock', 'ground'],
    baseAtk: 118, baseDef: 145, baseSta: 82,
    bcr: 0.15, fleeRate: 0.10, rarity: 'rare',
    biomes: BW.cave, time: TW.day,
    candy: 'pebbleclaw', evolvesTo: null, evolveCost: 0,
    desc: 'A jaw of living granite that swallows boulders and regurgitates them as shrapnel.',
  },
  {
    id: 'shadowpup', name: 'Shadowpup', emoji: '🐺',
    types: ['dark'],
    baseAtk: 68, baseDef: 52, baseSta: 55,
    bcr: 0.50, fleeRate: 0.35, rarity: 'common',
    biomes: BW.cave, time: TW.night,
    candy: 'shadowpup', evolvesTo: 'umbrawolf', evolveCost: 12,
    desc: 'A black-furred pup that only appears at dusk.',
  },
  {
    id: 'umbrawolf', name: 'Umbrawolf', emoji: '🐺',
    types: ['dark', 'ghost'],
    baseAtk: 115, baseDef: 92, baseSta: 78,
    bcr: 0.15, fleeRate: 0.12, rarity: 'rare',
    biomes: BW.cave, time: TW.night,
    candy: 'shadowpup', evolvesTo: null, evolveCost: 0,
    desc: 'A wolf made of compressed shadow. Its howl is heard only in darkness.',
  },
  {
    id: 'wraithling', name: 'Wraithling', emoji: '👻',
    types: ['ghost'],
    baseAtk: 62, baseDef: 48, baseSta: 58,
    bcr: 0.30, fleeRate: 0.30, rarity: 'uncommon',
    biomes: BW.cave, time: TW.night,
    candy: 'wraithling', evolvesTo: 'spectralord', evolveCost: 25,
    desc: 'A translucent child-shaped spirit that chases shadows.',
  },
  {
    id: 'spectralord', name: 'Spectralord', emoji: '👻',
    types: ['ghost', 'dragon'],
    baseAtk: 142, baseDef: 118, baseSta: 92,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.cave, time: TW.night,
    candy: 'wraithling', evolvesTo: null, evolveCost: 0,
    desc: 'A spectral dragon that haunts ancient ruins. It feeds on memories.',
  },

  // ── SKY / FLYING ───────────────────────────────────────────────────────────
  {
    id: 'zephyrkit', name: 'Zephyrkit', emoji: '🐦',
    types: ['flying'],
    baseAtk: 55, baseDef: 48, baseSta: 62,
    bcr: 0.50, fleeRate: 0.30, rarity: 'common',
    biomes: BW.sky, time: TW.day,
    candy: 'zephyrkit', evolvesTo: 'galewings', evolveCost: 12,
    desc: 'A small bird-like creature that rides thermals and sleeps on treetops.',
  },
  {
    id: 'galewings', name: 'Galewings', emoji: '🦅',
    types: ['flying'],
    baseAtk: 98, baseDef: 82, baseSta: 78,
    bcr: 0.30, fleeRate: 0.15, rarity: 'uncommon',
    biomes: BW.sky, time: TW.day,
    candy: 'zephyrkit', evolvesTo: 'tempestlord', evolveCost: 25,
    desc: 'A swift hawk with wings that generate their own updrafts.',
  },
  {
    id: 'tempestlord', name: 'Tempestlord', emoji: '🦅',
    types: ['flying', 'dragon'],
    baseAtk: 155, baseDef: 122, baseSta: 100,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.sky, time: TW.day,
    candy: 'zephyrkit', evolvesTo: null, evolveCost: 0,
    desc: 'A colossal raptor that rides hurricane eyes.',
  },
  {
    id: 'featherdrift', name: 'Featherdrift', emoji: '🪶',
    types: ['flying', 'grass'],
    baseAtk: 68, baseDef: 58, baseSta: 65,
    bcr: 0.50, fleeRate: 0.25, rarity: 'common',
    biomes: BW.sky, time: TW.day,
    candy: 'featherdrift', evolvesTo: null, evolveCost: 0,
    desc: 'A small creature covered in floating feathers that drifts between trees.',
  },
  {
    id: 'luminmoth', name: 'Luminmoth', emoji: '🦋',
    types: ['bug', 'flying'],
    baseAtk: 62, baseDef: 52, baseSta: 58,
    bcr: 0.50, fleeRate: 0.30, rarity: 'common',
    biomes: BW.sky, time: TW.night,
    candy: 'luminmoth', evolvesTo: null, evolveCost: 0,
    desc: 'A large moth with wings that glow like lanterns. It flies only at night.',
  },
  {
    id: 'crystalwing', name: 'Crystalwing', emoji: '🦋',
    types: ['flying', 'steel'],
    baseAtk: 92, baseDef: 88, baseSta: 72,
    bcr: 0.30, fleeRate: 0.15, rarity: 'uncommon',
    biomes: BW.sky, time: TW.day,
    candy: 'crystalwing', evolvesTo: null, evolveCost: 0,
    desc: 'A bird with wings of transparent crystal whose wingbeats make rainbows.',
  },

  // ── FOREST ─────────────────────────────────────────────────────────────────
  {
    id: 'venomcap', name: 'Venomcap', emoji: '🍄',
    types: ['poison'],
    baseAtk: 65, baseDef: 58, baseSta: 52,
    bcr: 0.50, fleeRate: 0.28, rarity: 'common',
    biomes: BW.forest, time: TW.even,
    candy: 'venomcap', evolvesTo: 'toxiqueen', evolveCost: 12,
    desc: 'A mushroom creature that releases toxic spores when threatened.',
  },
  {
    id: 'toxiqueen', name: 'Toxiqueen', emoji: '🍄',
    types: ['poison', 'dark'],
    baseAtk: 118, baseDef: 95, baseSta: 72,
    bcr: 0.15, fleeRate: 0.10, rarity: 'rare',
    biomes: BW.forest, time: TW.night,
    candy: 'venomcap', evolvesTo: null, evolveCost: 0,
    desc: 'A regal mushroom with a crown of toxic spores — beautiful and lethal.',
  },
  {
    id: 'barkguard', name: 'Barkguard', emoji: '🌲',
    types: ['grass', 'rock'],
    baseAtk: 102, baseDef: 138, baseSta: 85,
    bcr: 0.30, fleeRate: 0.10, rarity: 'uncommon',
    biomes: BW.forest, time: TW.day,
    candy: 'barkguard', evolvesTo: 'grovetitan', evolveCost: 25,
    desc: 'A tree-like creature with bark armor that stands motionless for months.',
  },
  {
    id: 'grovetitan', name: 'Grovetitan', emoji: '🌲',
    types: ['grass', 'dragon'],
    baseAtk: 152, baseDef: 145, baseSta: 108,
    bcr: 0.06, fleeRate: 0.08, rarity: 'epic',
    biomes: BW.forest, time: TW.day,
    candy: 'barkguard', evolvesTo: null, evolveCost: 0,
    desc: 'A colossal tree-dragon whose roots extend for miles.',
  },
  {
    id: 'mossling', name: 'Mossling', emoji: '🌿',
    types: ['grass'],
    baseAtk: 52, baseDef: 68, baseSta: 55,
    bcr: 0.50, fleeRate: 0.20, rarity: 'common',
    biomes: BW.forest, time: TW.day,
    candy: 'mossling', evolvesTo: 'fernclaw', evolveCost: 12,
    desc: 'A small moss-covered creature that is almost invisible until it moves.',
  },
  {
    id: 'fernclaw', name: 'Fernclaw', emoji: '🌿',
    types: ['grass', 'fighting'],
    baseAtk: 95, baseDef: 108, baseSta: 72,
    bcr: 0.15, fleeRate: 0.12, rarity: 'rare',
    biomes: BW.forest, time: TW.day,
    candy: 'mossling', evolvesTo: null, evolveCost: 0,
    desc: 'A muscular creature with fern-like fronds that punches through boulders.',
  },

  // ── LEGENDARY ──────────────────────────────────────────────────────────────
  {
    id: 'auroradrake', name: 'Aurora Drake', emoji: '🌠',
    types: ['electric', 'dragon'],
    baseAtk: 172, baseDef: 148, baseSta: 112,
    bcr: 0.02, fleeRate: 0.05, rarity: 'legendary',
    biomes: BW.sky, time: TW.dawn,
    candy: 'auroradrake', evolvesTo: null, evolveCost: 0,
    desc: 'A legendary serpent of northern lights that vanishes at dawn.',
  },
  {
    id: 'voidseraph', name: 'Void Seraph', emoji: '🌑',
    types: ['ghost', 'dragon'],
    baseAtk: 168, baseDef: 142, baseSta: 108,
    bcr: 0.02, fleeRate: 0.05, rarity: 'legendary',
    biomes: BW.cave, time: TW.dawn,
    candy: 'voidseraph', evolvesTo: null, evolveCost: 0,
    desc: 'A six-winged entity from the void between stars.',
  },
  {
    id: 'solarphoenix', name: 'Solar Phoenix', emoji: '🦅',
    types: ['fire', 'flying'],
    baseAtk: 175, baseDef: 138, baseSta: 110,
    bcr: 0.02, fleeRate: 0.05, rarity: 'legendary',
    biomes: BW.sky, time: TW.dawn,
    candy: 'solarphoenix', evolvesTo: null, evolveCost: 0,
    desc: 'A bird made of compressed sunlight, reborn from its own ash.',
  },
  {
    id: 'abyssalwyrm', name: 'Abyssal Wyrm', emoji: '🐋',
    types: ['water', 'dragon'],
    baseAtk: 165, baseDef: 155, baseSta: 105,
    bcr: 0.02, fleeRate: 0.05, rarity: 'legendary',
    biomes: BW.water, time: TW.dawn,
    candy: 'abyssalwyrm', evolvesTo: null, evolveCost: 0,
    desc: 'A leviathan from the deepest trenches. Its scales light up the ocean floor.',
  },
  {
    id: 'chronowisp', name: 'Chrono Wisp', emoji: '🌟',
    types: ['ghost', 'flying'],
    baseAtk: 148, baseDef: 125, baseSta: 98,
    bcr: 0.02, fleeRate: 0.05, rarity: 'legendary',
    biomes: BW.sky, time: TW.dawn,
    candy: 'chronowisp', evolvesTo: null, evolveCost: 0,
    desc: 'A spectral bird outside of time. Catching one means you caught it yesterday.',
  },
]

export const SPECIES_BY_ID = Object.fromEntries(SPECIES.map(s => [s.id, s]))
